apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dply
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-pod
  template:
    metadata:
      labels:
        app: back-pod # <- the key man
        tier: backend 
    spec: 
      containers:
        - name: back
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080     
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service ## the frontend reverse proxy will need this name
spec:
  selector:
    app: back-pod
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: front-dply
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-pod
  template: 
    metadata:
      labels: 
        app: front-pod
        tier: frontend
    spec: 
      containers: 
        - name: front
          image: stacksimplify/kube-frontend-nginx:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: all-in-one-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: front-pod
  ports: 
    - name: http
      port: 80