apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-app1-app2-app3-ssl
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml
    cert-manager.io/cluster-issuer: letsencrypt 
spec:
  rules:
  - host: dev.det.asia
    http:
      paths:
      - path: /
        backend:
          serviceName: app2-nginx-clusterip-service
          servicePort: 80
  - host: test.det.asia
    http:
      paths:
      - path: /
        backend:
          serviceName: usermgmt-webapp-clusterip-service
          servicePort: 80  
  - host: det.asia
    http:
      paths:
      - path: /
        backend:
          serviceName: app1-nginx-clusterip-service
          servicePort: 80          
  tls:
  - hosts:
    - det.asia
    secretName: det-asia-secret
  - hosts:
    - dev.det.asia
    secretName: dev-det-asia-secret
  - hosts:
    - test.det.asia
    secretName: test-det-asia-secret
                     